# Generated by Django 5.0.2 on 2024-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('license_ID', models.CharField(blank=True, max_length=20)),
                ('license_category', models.CharField(choices=[('AM', 'AM'), ('A1', 'A1'), ('A2', 'A2'), ('A', 'A'), ('B', 'B'), ('BE', 'BE'), ('W', 'W'), ('C', 'C'), ('CE', 'CE'), ('C1', 'C1'), ('C1E', 'C1E'), ('D', 'D'), ('DE', 'DE'), ('D1', 'D1'), ('D1E', 'D1E')], default='category', max_length=15)),
                ('photo', models.ImageField(blank=True, default='user.png', upload_to='image/drivers')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
