# Generated by Django 5.0.2 on 2024-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(blank=True, max_length=100)),
                ('bus_type', models.CharField(choices=[('Coach / Motor', 'Coach / Motor'), ('Coach', 'Coach'), ('School Bus', 'School Bus'), ('Shuttle', 'Shuttle'), ('Minibus', 'Minibus'), ('MiniCoach', 'MiniCoach'), ('Single-decker', 'Single-decker'), ('Double-decker', 'Double-decker'), ('Low-floor', 'Low-floor'), ('Other', 'Other')], default='Double-decker', max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=20)),
                ('cost_per_day', models.FloatField(default=0)),
                ('registration_plate', models.CharField(blank=True, max_length=50)),
                ('bus_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Needs Servicing', 'Needs Servicing'), ('Needs Repairs', 'Needs Repairs'), ('Other', 'Other')], default='Healthy', max_length=20)),
                ('insurance_status', models.ImageField(blank=True, default='insure.png', upload_to='image/insurance')),
                ('speed', models.FloatField(default=0)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Propane', 'Propane'), ('Gasoline', 'Gasoline'), ('Ethanol', 'Ethanol'), ('CNG', 'CNG'), ('Hybrid', 'Hybrid'), ('Biodiesel', 'Biodiesel'), ('Fuel Oil', 'Fuel Oil'), ('Electricity', 'Electricity'), ('Other', 'Other')], default='petrol', max_length=25)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='car.png', upload_to='image/vehicles')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
