# Generated by Django 5.0.2 on 2024-03-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='capacity',
            field=models.FloatField(max_length=20),
        ),
    ]
