# Generated by Django 5.0.2 on 2024-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicles_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='capacity',
            field=models.FloatField(default=0),
        ),
    ]
