# Generated by Django 5.0.2 on 2024-03-04 08:57

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('distance', models.IntegerField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('security_deposit', models.IntegerField(blank=True)),
                ('cost', models.IntegerField(blank=True)),
                ('booker', models.CharField(blank=True, max_length=250)),
                ('booker_phone', models.CharField(blank=True, max_length=50)),
                ('assigned_driver', models.CharField(blank=True, max_length=100)),
                ('notes', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
